spring:
  application:
    name: user-server
  datasource:
    # 配置数据源类型
    type:
      com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.9.181:3306/item?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
    # 初始化，最小，最大连接数
    initialSize: 3
    minidle: 3
    maxActive: 18
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM dual
    # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计
    filters: stat,wall,log4j

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


dubbo:
  protocol:
    name: dubbo
    port: 20880
    #指定zookeeper注册中心地址和端口号
  registry:
    address: zookeeper://47.93.9.181:2181
  scan:
    base-packages:  com.xishan.store.usercenter.userapi.facade
logging:
  level:
    root: info
  redis:
    database: 0
    host: 47.93.9.181
    password:
    port: 6372
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 5000
elasticsearch:
  ip: 47.93.9.181:9200